# Wazuh Agent Configuration for IT-SOC Home Lab
# This configuration file defines settings for Wazuh agents deployed on Windows endpoints
# in the lab environment for endpoint detection and response capabilities.

# Global Wazuh Agent settings
<ossec_config>
<client>
<server>
<address>10.1.10.10</address>
<port>1514</port>
<protocol>tcp</protocol>
</server>
<crypto_method>aes</crypto_method>
<notify_time>10</notify_time>
<time-reconnect>60</time-reconnect>
<auto_restart>yes</auto_restart>
</client>

<!-- File Integrity Monitoring -->
<syscheck>
<disabled>no</disabled>
<frequency>43200</frequency>

<!-- Windows Registry Monitoring -->
<windows_registry>HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run</windows_registry>
<windows_registry>HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce</windows_registry>
<windows_registry>HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon</windows_registry>
<windows_registry>HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services</windows_registry>
<windows_registry>HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\KnownDLLs</windows_registry>
<windows_registry>HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies</windows_registry>

<!-- Critical System Files -->
<directories check_all="yes" realtime="yes">C:\Windows\System32\drivers\etc</directories>
<directories check_all="yes" realtime="yes">C:\Windows\System32\wbem</directories>
<directories check_all="yes" realtime="yes">C:\Windows\System32\WindowsPowerShell</directories>
<directories check_all="yes" realtime="yes">C:\Program Files\Microsoft Security Client</directories>

<!-- User Profile Monitoring -->
<directories check_all="yes" realtime="yes">C:\Users\*\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup</directories>

<!-- Ignore frequently changing files -->
<ignore>C:\Windows\system32\wbem\Repository</ignore>
<ignore>C:\Windows\SoftwareDistribution</ignore>
<ignore>C:\Windows\Prefetch</ignore>
<ignore>C:\Windows\Temp</ignore>

<!-- Skip nfs/smbfs/tmpfs since it causes problems -->
<skip_nfs>yes</skip_nfs>
<skip_dev>yes</skip_dev>
<skip_proc>yes</skip_proc>
<skip_sys>yes</skip_sys>

<!-- Maximum FIM file size -->
<max_files_per_second>1000</max_files_per_second>
</syscheck>

<!-- Log Analysis -->
<localfile>
<location>Security</location>
<log_format>eventchannel</log_format>
</localfile>

<localfile>
<location>System</location>
<log_format>eventchannel</log_format>
</localfile>

<localfile>
<location>Application</location>
<log_format>eventchannel</log_format>
</localfile>

<localfile>
<location>Microsoft-Windows-Sysmon/Operational</location>
<log_format>eventchannel</log_format>
</localfile>

<localfile>
<location>Microsoft-Windows-PowerShell/Operational</location>
<log_format>eventchannel</log_format>
</localfile>

<localfile>
<location>Microsoft-Windows-Windows Defender/Operational</location>
<log_format>eventchannel</log_format>
</localfile>

<!-- Active Response Configuration -->
<active-response>
<disabled>no</disabled>
<ca_store>wpk_root.pem</ca_store>
<ca_verification>yes</ca_verification>
</active-response>

<!-- Rootcheck Configuration -->
<rootcheck>
<disabled>no</disabled>
<check_unixaudit>no</check_unixaudit>
<check_files>yes</check_files>
<check_trojans>yes</check_trojans>
<check_dev>no</check_dev>
<check_sys>no</check_sys>
<check_pids>yes</check_pids>
<check_ports>yes</check_ports>
<check_if>yes</check_if>
<frequency>36000</frequency>
<rootkit_files>C:\Program Files (x86)\ossec-agent\shared\rootkit_files.txt</rootkit_files>
<rootkit_trojans>C:\Program Files (x86)\ossec-agent\shared\rootkit_trojans.txt</rootkit_trojans>
<skip_nfs>yes</skip_nfs>
</rootcheck>

<!-- Wodle for Windows Event Channel -->
<wodle name="syscollector">
<disabled>no</disabled>
<interval>1h</interval>
<scan_on_start>yes</scan_on_start>
<hardware>yes</hardware>
<os>yes</os>
<network>yes</network>
<packages>yes</packages>
<ports all="yes">yes</ports>
<processes>yes</processes>
</wodle>

<!-- SCA (Security Configuration Assessment) -->
<sca>
<enabled>yes</enabled>
<scan_on_start>yes</scan_on_start>
<interval>12h</interval>
<skip_nfs>yes</skip_nfs>
</sca>

<!-- Vulnerability Detector -->
<vulnerability-detector>
<enabled>yes</enabled>
<interval>24h</interval>
<ignore_time>6h</ignore_time>
<run_on_start>yes</run_on_start>

<provider name="nvd">
<enabled>yes</enabled>
<update_from_year>2010</update_from_year>
<update_interval>1h</update_interval>
</provider>
</vulnerability-detector>

<!-- Command Monitoring -->
<command>
<name>win_audit_policy</name>
<executable>C:\Program Files (x86)\ossec-agent\active-response\bin\win_audit_policy.exe</executable>
<expect>system</expect>
<timeout_allowed>no</timeout_allowed>
</command>

<!-- Syslog Output to Security Onion -->
<syslog_output>
<server>10.1.10.10</server>
<port>514</port>
<format>default</format>
</syslog_output>

<!-- Labels for Agent Identification -->
<labels>
<label key="network">SOC-Network</label>
<label key="role">workstation</label>
<label key="environment">lab</label>
</labels>
</ossec_config>
